a = int(input("enter the number"))
b = int(input("enter the number"))
c = int(input("enter the number"))
d = int(input("enter the number"))
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)
print(a != b)
print(a == b)
if a < b and c < d:
    print("true")
if a < b or c < d:
    print("true")
if not a < b and c < d:
    print("true")

a = str(input("enter the number"))
b = str(input("enter the number"))
print(a + b)
